Update smoltcp version to 0.13
fix(tcp): prevent integer underflow in sequence number calculation

Fixes a bug in smoltcp v0.12.0 where certain boundary conditions 
caused an integer underflow during TCP sequence number computations, 
leading to a panic.

This issue has been addressed by backporting/applying the fix 
from v0.13.0.

thread 'tokio-rt-worker' (29403) panicked at index.crates.io-1949cf8c6b5b557f/smoltcp-0.12.0/src/wire/tcp.rs:81:13:
attempt to subtract sequence numbers with underflow